# Generated by Django 6.0.3 on 2026-03-18 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('public_description', models.TextField(help_text='Describe the item vaguely — DO NOT include serial numbers, passwords, or secret details. E.g. "A black electronic device"', verbose_name='Public Description (vague)')),
                ('private_description', models.TextField(help_text='Full details: exact colour, markings, serial number, contents — only admin and verified owner will see this', verbose_name='Private Description (confidential)')),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing & Accessories'), ('books', 'Books & Stationery'), ('documents', 'Documents & IDs'), ('keys', 'Keys'), ('bags', 'Bags & Backpacks'), ('jewelry', 'Jewelry & Watches'), ('sports', 'Sports Equipment'), ('money', 'Money & Cards'), ('other', 'Other')], max_length=50)),
                ('location_found', models.CharField(choices=[('library', 'Library'), ('cafeteria', 'Cafeteria'), ('lecture_hall', 'Lecture Hall'), ('hostel', 'Hostel / Dormitory'), ('sports_ground', 'Sports Ground'), ('parking', 'Parking Area'), ('admin_block', 'Administration Block'), ('lab', 'Laboratory'), ('chapel', 'Chapel / Mosque'), ('clinic', 'Health Clinic'), ('other', 'Other')], max_length=50)),
                ('location_detail', models.CharField(blank=True, help_text='Exact spot — this is kept private and not shown publicly', max_length=200)),
                ('date_found', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_items/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('current_holding', models.CharField(blank=True, help_text='Where is the item currently kept? (private)', max_length=200)),
                ('verif_color', models.CharField(blank=True, help_text='Exact colour, brand, or appearance as you found it', max_length=100, verbose_name='Colour / appearance observed')),
                ('verif_distinguishing', models.CharField(blank=True, help_text='Any scratches, stickers, engravings, or unique marks you noticed', max_length=200, verbose_name='Distinguishing features observed')),
                ('verif_secret', models.CharField(blank=True, help_text='Any other detail not visible from outside (e.g. item inside a bag, note tucked in)', max_length=200, verbose_name='Additional private detail')),
                ('status', models.CharField(choices=[('available', 'Available'), ('matched', 'Matched'), ('returned', 'Returned'), ('unclaimed', 'Unclaimed - Donated')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoundItemView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='items.founditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_item_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing & Accessories'), ('books', 'Books & Stationery'), ('documents', 'Documents & IDs'), ('keys', 'Keys'), ('bags', 'Bags & Backpacks'), ('jewelry', 'Jewelry & Watches'), ('sports', 'Sports Equipment'), ('money', 'Money & Cards'), ('other', 'Other')], max_length=50)),
                ('location_lost', models.CharField(choices=[('library', 'Library'), ('cafeteria', 'Cafeteria'), ('lecture_hall', 'Lecture Hall'), ('hostel', 'Hostel / Dormitory'), ('sports_ground', 'Sports Ground'), ('parking', 'Parking Area'), ('admin_block', 'Administration Block'), ('lab', 'Laboratory'), ('chapel', 'Chapel / Mosque'), ('clinic', 'Health Clinic'), ('other', 'Other')], max_length=50)),
                ('location_detail', models.CharField(blank=True, max_length=200)),
                ('date_lost', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('proof_of_ownership', models.ImageField(blank=True, help_text='Upload a previous photo, receipt, or any proof this item belongs to you', null=True, upload_to='ownership_proof/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('reward', models.CharField(blank=True, max_length=100)),
                ('verif_color', models.CharField(blank=True, help_text='Describe the exact colour, brand markings, or appearance', max_length=100, verbose_name='Item colour / appearance')),
                ('verif_distinguishing', models.CharField(blank=True, help_text='Any scratches, stickers, engravings, or unique marks?', max_length=200, verbose_name='Distinguishing feature')),
                ('verif_secret', models.CharField(blank=True, help_text='Something only you would know (e.g. lock screen wallpaper, bag contents, note inside)', max_length=200, verbose_name='Secret detail')),
                ('status', models.CharField(choices=[('active', 'Active'), ('matched', 'Matched'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('fraud_risk', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk — Review Carefully')], default='low', max_length=10)),
                ('fraud_flags', models.TextField(blank=True, help_text='Auto-detected fraud warning flags')),
                ('reporter_viewed_found_before_reporting', models.BooleanField(default=False, help_text='True if reporter viewed this found item BEFORE submitting their lost report')),
                ('verif_color_match', models.BooleanField(blank=True, null=True, verbose_name='Colour answers match?')),
                ('verif_distinguishing_match', models.BooleanField(blank=True, null=True, verbose_name='Distinguishing feature answers match?')),
                ('verif_secret_match', models.BooleanField(blank=True, null=True, verbose_name='Secret detail answers match?')),
                ('admin_verif_notes', models.TextField(blank=True, verbose_name='Admin verification notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_notified', models.BooleanField(default=False)),
                ('finder_notified', models.BooleanField(default=False)),
                ('owner_confirmed', models.BooleanField(blank=True, null=True)),
                ('finder_confirmed', models.BooleanField(blank=True, null=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='items.founditem')),
                ('matched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_matches', to=settings.AUTH_USER_MODEL)),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='items.lostitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('lost_item', 'found_item')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('match_found', 'Potential Match Found'), ('match_approved', 'Match Approved'), ('match_rejected', 'Match Rejected'), ('item_returned', 'Item Returned'), ('new_lost', 'New Lost Item Posted'), ('new_found', 'New Found Item Posted'), ('fraud_alert', 'Fraud Alert')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.itemmatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
